---
title: "Sandbox"
author: "Waveley Qiu"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: pdf_document
header-includes:
  - \usepackage{mathrsfs}
  - \usepackage{amsfonts}  
---


```{r setup, include=FALSE}
set.seed(20220417)
library(tidyverse)
library(lme4)
library(lmerTest)

# set knitr defaults
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center",
  fig.width = 6,
  fig.asp   = .6,
  out.width = "90%",
  cache = TRUE
)

# set theme defaults
theme_set(
  theme_bw() +
    theme(
      legend.position = "bottom",
      plot.title    = element_text(hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5),
      plot.caption  = element_text(hjust = 0.0)
    )
)

# set color scale defaults
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill   = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete   = scale_fill_viridis_d
```

# Read Data

```{r}
diet_sleep <- readxl::read_excel("data/CM + DQ Study Diet and Sleep_8.24.2022_HB.xlsx", sheet = "Diet-sleep") %>%
  janitor::clean_names() %>%
  filter(
    condition == "Aligned"
  )

lm1 <- lmer("se ~ sex + age + bmi + en + (1 | id)", data = diet_sleep)
lm1 <- lmer("se ~ age  + en + (1 | id)", data = diet_sleep)
saved_sum <- lm1 %>% summary()
new_vec <- saved_sum$coefficients[,5]
names <- new_vec[new_vec < 0.05] %>% names()
names[!(names %in% c("(Intercept)"))]


outcomes <-
  diet_sleep %>%
  select(
    se,
    tst,
    waso, 
    sfi
  )
covariates <-
  diet_sleep %>%
  select(
    sex, age, bmi
  )
predictors <- 
  diet_sleep %>%
  select(
    en, food_wt_f, ed, prot, fat, cho, prot_plant, prot_ani, fiber,
    ca, mg, na, zn, vit_b6, vit_b12, sfa, ufa, vit_d, fruit, veg, f_v,
    egg, nuts, dairy, added_sugar
  )

i = 1
j = 1
pred_name <- predictors[,i] %>% names()
outcome_name <- outcomes[,j] %>% names()
print(paste0(outcome_name, " vs ", pred_name))
cur_outcome <- outcomes %>% pull(outcome_name)
cur_predictor <- predictors %>% pull(pred_name)
age <- diet_sleep %>% pull(age)
sex <- diet_sleep %>% pull(sex)
bmi <- diet_sleep %>% pull(bmi)
id <- diet_sleep %>% pull(id)
test_lmer <- lmer("cur_outcome ~ sex + age + bmi + cur_predictor + (1 | id)")


sleep_diet <- readxl::read_excel("data/CM + DQ Study Diet and Sleep_8.24.2022_HB.xlsx", sheet = "Sleep-diet")
```

